import type { Lesson } from '../components';

export const ADVANCED_FALLBACK_LESSON: Lesson = {
  id: 'en-card-hospital-directions-advanced-test',
  language: 'en',
  title: 'Hospital directions test dialogue',
  mode: 'ai_guided_response',
  stage: 'guided_scene_production',
  player_component: 'TravellerLessonPlayer',
  target: {
    id: 'en-target-where-is-hospital',
    text: 'Where is the hospital?',
    transliteration: '',
    meaning: 'Ask where the hospital is.',
  },
  frames: [
    {
      id: 'line-0',
      lineIndex: 0,
      frameNumber: 1,
      imageUrl: '/visuals/final/directions-hospital/frame-1.png',
      audioUrl: '/audio/generated/en/en-directions-hospital/line-0.mp3',
      title: 'World Opener',
      speaker: 'local',
      text: 'Can I help you?',
      transliteration: '',
      lineType: 'world_opener',
    },
    {
      id: 'line-1',
      lineIndex: 1,
      frameNumber: 2,
      imageUrl: '/visuals/final/directions-hospital/frame-2.png',
      audioUrl: '/audio/generated/en/en-directions-hospital/line-1.mp3',
      title: 'Learner Target',
      speaker: 'learner',
      text: 'Where is the hospital?',
      transliteration: '',
      lineType: 'learner_target',
    },
    {
      id: 'line-2',
      lineIndex: 2,
      frameNumber: 3,
      imageUrl: '/visuals/final/directions-hospital/frame-3.png',
      audioUrl: '/audio/generated/en/en-directions-hospital/line-2.mp3',
      title: 'World Response',
      speaker: 'local',
      text: 'It is two blocks that way.',
      transliteration: '',
      lineType: 'world_response',
    },
  ],
  steps: [
    {
      id: 'scene_setup',
      type: 'scene_setup',
      component: 'SceneFrame',
      frameId: 'line-0',
      frameMode: 'single',
      displayText: 'Listen.',
      audio: {
        url: '/audio/generated/en/en-directions-hospital/line-0.mp3',
        autoplay: true,
        replayable: true,
        playBeforeMic: false,
      },
      mic: {
        enabled: false,
        record: false,
        scoring: 'none',
      },
      props: {
        initialFrameId: 'line-0',
        frames: [],
      },
    },
    {
      id: 'target_audio',
      type: 'target_audio',
      component: 'AudioButton',
      frameId: 'line-1',
      frameMode: 'single',
      displayText: 'Listen to what they say.',
      audio: {
        url: '/audio/generated/en/en-directions-hospital/line-1.mp3',
        autoplay: true,
        replayable: true,
        playBeforeMic: false,
      },
      mic: {
        enabled: false,
        record: false,
        scoring: 'none',
      },
      props: {
        audioUrl: '/audio/generated/en/en-directions-hospital/line-1.mp3',
        text: {
          playLabel: 'Play',
          playingLabel: 'Playing',
        },
      },
    },
    {
      id: 'broad_meaning_guess',
      type: 'broad_meaning_guess',
      component: 'ChoicePrompt',
      frameId: 'line-2',
      frameMode: 'single',
      displayText: 'What happened?',
      audio: {
        url: '/audio/generated/en/en-directions-hospital/line-1.mp3',
        autoplay: false,
        replayable: true,
        playBeforeMic: false,
      },
      mic: {
        enabled: false,
        record: false,
        scoring: 'none',
      },
      props: {
        question: 'What happened?',
        choices: [
          {
            id: 'ask_hospital',
            label: 'They asked where the hospital is.',
            isCorrect: true,
          },
          {
            id: 'order_food',
            label: 'They ordered food politely.',
            isCorrect: false,
          },
          {
            id: 'say_name',
            label: 'They introduced themself.',
            isCorrect: false,
          },
          {
            id: 'do_not_understand',
            label: 'They said they did not understand.',
            isCorrect: false,
          },
        ],
      },
    },
    {
      id: 'repeat_with_mic',
      type: 'repeat_with_mic',
      component: 'MicPrompt',
      frameId: 'line-1',
      frameMode: 'single',
      displayText: 'Now say it.',
      audio: {
        url: '/audio/generated/en/en-directions-hospital/line-1.mp3',
        autoplay: true,
        replayable: true,
        playBeforeMic: true,
      },
      mic: {
        enabled: true,
        record: true,
        startsAfterAudio: true,
        expectedText: 'Where is the hospital?',
        expectedTransliteration: '',
        scoring: 'deferred',
        continueOnRecord: true,
        blockingFeedback: false,
      },
      props: {
        expectedText: 'Where is the hospital?',
        expectedTransliteration: '',
      },
    },
    {
      id: 'backward_build',
      type: 'backward_build',
      component: 'BackwardBuild',
      frameId: 'line-1',
      frameMode: 'neutral',
      displayText: 'Build it from the end.',
      audio: {
        url: '/audio/generated/en/en-directions-hospital/line-1.mp3',
        autoplay: false,
        replayable: true,
        playBeforeMic: false,
      },
      mic: {
        enabled: true,
        record: true,
        startsAfterAudio: false,
        expectedText: 'Where is the hospital?',
        expectedTransliteration: '',
        scoring: 'deferred',
        continueOnRecord: true,
        blockingFeedback: false,
      },
      props: {
        targetPhrase: 'Where is the hospital?',
        chunks: [
          { id: 'where', text: 'Where', meaning: 'asking for a place' },
          { id: 'is', text: 'is', meaning: 'location link' },
          { id: 'the-hospital', text: 'the hospital', meaning: 'the place needed' },
        ],
        prompts: [
          {
            id: 'build-hospital',
            text: 'hospital',
            audioUrl: '/audio/generated/en/en-directions-hospital/line-1.mp3',
          },
          {
            id: 'build-the-hospital',
            text: 'the hospital',
            audioUrl: '/audio/generated/en/en-directions-hospital/line-1.mp3',
          },
          {
            id: 'build-is-the-hospital',
            text: 'is the hospital',
            audioUrl: '/audio/generated/en/en-directions-hospital/line-1.mp3',
          },
          {
            id: 'build-where-is-the-hospital',
            text: 'Where is the hospital?',
            audioUrl: '/audio/generated/en/en-directions-hospital/line-1.mp3',
          },
        ],
      },
    },
    {
      id: 'scene_recall',
      type: 'scene_recall',
      component: 'SceneFrame',
      frameId: 'line-0',
      frameMode: 'single',
      displayText: 'What would you say?',
      audio: {
        url: '/audio/generated/en/en-directions-hospital/line-0.mp3',
        autoplay: true,
        replayable: true,
        playBeforeMic: true,
      },
      mic: {
        enabled: true,
        record: true,
        startsAfterAudio: true,
        expectedText: 'Where is the hospital?',
        expectedTransliteration: '',
        scoring: 'deferred',
        continueOnRecord: true,
        blockingFeedback: false,
      },
      props: {
        initialFrameId: 'line-0',
        frames: [],
      },
    },
  ],
};
