import type { Lesson } from '../components';

export const FALLBACK_LESSON: Lesson = {
  id: 'en-card-first-hi-dialogue-practice',
  language: 'en',
  title: 'First hello dialogue',
  mode: 'ai_guided_response',
  stage: 'guided_scene_production',
  target: {
    id: 'en-target-respond-hi',
    text: 'Hi!',
    transliteration: '',
    meaning: 'Respond to Hi.',
  },
  frames: [
    {
      id: 'line-0',
      lineIndex: 0,
      frameNumber: 1,
      imageUrl: '/visuals/final/first-hi-response/frame-1.png',
      audioUrl: '/audio/generated/en/en-first-hi-response/line-0.mp3',
      title: 'World Opener',
      speaker: 'friend',
      text: 'Hi!',
      transliteration: '',
      lineType: 'world_opener',
    },
    {
      id: 'line-1',
      lineIndex: 1,
      frameNumber: 2,
      imageUrl: '/visuals/final/first-hi-response/frame-2.png',
      audioUrl: '/audio/generated/en/en-first-hi-response/line-1.mp3',
      title: 'Learner Target',
      speaker: 'learner',
      text: 'Hi!',
      transliteration: '',
      lineType: 'learner_target',
    },
    {
      id: 'line-2',
      lineIndex: 2,
      frameNumber: 3,
      imageUrl: '/visuals/final/first-hi-response/frame-3.png',
      audioUrl: '/audio/generated/en/en-first-hi-response/line-2.mp3',
      title: 'World Response',
      speaker: 'friend',
      text: 'Nice to see you.',
      transliteration: '',
      lineType: 'world_response',
    },
  ],
  steps: [
    {
      id: 'scene_setup',
      type: 'scene_setup',
      component: 'SceneFrame',
      frameId: 'line-0',
      frameMode: 'single',
      displayText: 'Listen.',
      audio: {
        url: '/audio/generated/en/en-first-hi-response/line-0.mp3',
        audioText: 'Hi!',
        autoplay: true,
        replayable: true,
        playBeforeMic: false,
      },
      mic: {
        enabled: false,
        record: false,
        scoring: 'none',
      },
      props: {
        initialFrameId: 'line-0',
        frames: [
          {
            id: 'line-0',
            lineIndex: 0,
            frameNumber: 1,
            imageUrl: '/visuals/final/first-hi-response/frame-1.png',
            audioUrl: '/audio/generated/en/en-first-hi-response/line-0.mp3',
            title: 'World Opener',
            speaker: 'friend',
            text: 'Hi!',
            transliteration: '',
            lineType: 'world_opener',
          },
          {
            id: 'line-1',
            lineIndex: 1,
            frameNumber: 2,
            imageUrl: '/visuals/final/first-hi-response/frame-2.png',
            audioUrl: '/audio/generated/en/en-first-hi-response/line-1.mp3',
            title: 'Learner Target',
            speaker: 'learner',
            text: 'Hi!',
            transliteration: '',
            lineType: 'learner_target',
          },
          {
            id: 'line-2',
            lineIndex: 2,
            frameNumber: 3,
            imageUrl: '/visuals/final/first-hi-response/frame-3.png',
            audioUrl: '/audio/generated/en/en-first-hi-response/line-2.mp3',
            title: 'World Response',
            speaker: 'friend',
            text: 'Nice to see you.',
            transliteration: '',
            lineType: 'world_response',
          },
        ],
      },
    },
    {
      id: 'broad_meaning_guess',
      type: 'broad_meaning_guess',
      component: 'ChoicePrompt',
      frameId: 'line-2',
      frameMode: 'single',
      displayText: 'What happened?',
      audio: {
        url: '/audio/generated/en/en-first-hi-response/line-1.mp3',
        audioText: 'Hi!',
        autoplay: false,
        replayable: true,
        playBeforeMic: false,
      },
      mic: {
        enabled: false,
        record: false,
        scoring: 'none',
      },
      props: {
        question: 'What happened?',
        choices: [
          {
            id: 'respond_to_greeting',
            label: 'They greeted the person back.',
            isCorrect: true,
          },
          {
            id: 'say_goodbye',
            label: 'They said goodbye.',
            isCorrect: false,
          },
          {
            id: 'ask_location',
            label: 'They asked where something is.',
            isCorrect: false,
          },
          {
            id: 'apologize',
            label: 'They apologized.',
            isCorrect: false,
          },
        ],
      },
    },
    {
      id: 'repeat_with_mic',
      type: 'repeat_with_mic',
      component: 'MicPrompt',
      frameId: 'line-1',
      frameMode: 'single',
      displayText: 'Now you say it.',
      audio: {
        url: '/audio/generated/en/en-first-hi-response/line-1.mp3',
        autoplay: true,
        replayable: true,
        playBeforeMic: true,
      },
      mic: {
        enabled: true,
        record: true,
        startsAfterAudio: true,
        scoring: 'deferred',
        continueOnRecord: true,
        blockingFeedback: false,
      },
      props: {
        expectedText: 'Hi!',
        expectedTransliteration: '',
      },
    },
  ],
};
